<a href="https://colab.research.google.com/github/Elizaluckianchikova/Algorithms-and-data-structure/blob/main/Ancestor's_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задача про поколения и предки **

Вычисление количества предков в генеалогическом дереве обычно основывается на принципах теории вероятностей. Существует несколько подходов к решению этой задачи, но одним из наиболее распространенных является использование формулы для подсчета количества предков на каждом поколении.

Один из возможных алгоритмов для вычисления количества предков в генеалогическом дереве может быть следующим:

1. Задать число поколений, для которых требуется рассчитать количество предков.
2. Начать с первого поколения (например, самих родителей).
3. Для каждого поколения вычислить количество предков, используя формулу: 2 в степени номер поколения.
4. Продолжить этот процесс для каждого поколения до желаемого числа поколений.

Пример:

Если у вас есть 5 поколений, то количество предков будет следующим:

- Первое поколение (родители): 2^1 = 2 предка.
- Второе поколение (дедушки и бабушки): 2^2 = 4 предка.
- Третье поколение (прадедушки и прабабушки): 2^3 = 8 предков.
- Четвертое поколение: 2^4 = 16 предков.
- Пятое поколение: 2^5 = 32 предка.

Таким образом, в результате этого алгоритма вы получите количество предков для каждого поколения в генеалогическом дереве.

Этот алгоритм основан на простой модели, которая подходит для рассчетов на начальном этапе. Однако в реальности генеалогические деревья могут быть более сложными, и для более точных расчетов могут потребоваться более сложные методы, учитывающие дополнительные факторы, такие как браки между родственниками и другие особенности генеалогической структуры.

**Модель Кимуры**

Модель Кимуры - это одна из моделей эволюции, которая учитывает вероятности различных типов мутаций при эволюции последовательностей ДНК или белков. Эта модель была разработана Мотоо Кимурой в 1980 году и является улучшенной версией модели Йукавы-Касиды, которая учитывает вероятность перехода между двумя состояниями (нуклеотидами) и вероятность трансверсии (замены на другой тип нуклеотида).

Модель Кимуры учитывает два типа мутаций: переходы (когда один тип нуклеотида заменяется на другой тип в пределах пурина или пиримидина) и трансверсии (когда один тип нуклеотида заменяется на другой тип между пуриными и пиримидиновыми нуклеотидами). Эта модель позволяет более точно оценивать расстояния между последовательностями и строить филогенетические деревья.

Модель Кимуры широко используется в биоинформатике и филогенетике для анализа эволюционных отношений и оценки генетических расстояний между организмами на основе их генетических последовательностей.
Она основана на методе опорных векторов (SVM) и часто используется в задачах классификации.

Этот код демонстрирует создание модели Кимуры с использованием библиотеки scikit-learn и предсказание вероятностей принадлежности объектов к классам.

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

# Загрузка данных
iris = load_iris()
X = iris.data
y = iris.target

# Разделение данных на обучающий и тестовый наборы
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Создание и обучение модели
model = SVC(kernel='rbf', probability=True)
model.fit(X_train, y_train)

# Предсказание вероятностей принадлежности к классам для тестового набора
proba = model.predict_proba(X_test)
print(proba)


[[0.00729844 0.90796347 0.08473809]
 [0.94620674 0.03768499 0.01610826]
 [0.01818741 0.00253626 0.97927633]
 [0.00778479 0.91151641 0.0806988 ]
 [0.00951896 0.82527912 0.16520192]
 [0.95419863 0.03274755 0.01305382]
 [0.02682419 0.96629383 0.00688198]
 [0.01291815 0.07996179 0.90712006]
 [0.0075439  0.82215277 0.17030333]
 [0.01272057 0.9818966  0.00538283]
 [0.01178832 0.16533852 0.82287316]
 [0.96533962 0.02382808 0.0108323 ]
 [0.9708013  0.01846917 0.01072953]
 [0.9616592  0.02702252 0.01131827]
 [0.97042176 0.01848514 0.01109309]
 [0.01064313 0.84838806 0.14096881]
 [0.0079389  0.00340092 0.98866019]
 [0.0115379  0.9823916  0.0060705 ]
 [0.00741472 0.93114933 0.06143595]
 [0.00799201 0.00558861 0.98641939]
 [0.95740903 0.03043065 0.01216032]
 [0.01142907 0.39010563 0.5984653 ]
 [0.95401049 0.03313507 0.01285444]
 [0.00810284 0.00745022 0.98444694]
 [0.02069778 0.0108997  0.96840252]
 [0.01066225 0.03944419 0.94989356]
 [0.00880793 0.00715127 0.9840408 ]
 [0.00886811 0.00306769 0.98

**Алгоритм для вычисления количества предков , где предков больше миллиона.**
Для вычисления количества предков, превышающего миллион, можно использовать алгоритм, который учитывает более сложные модели эволюции и увеличивает точность подсчета. Один из способов - использовать более сложные модели мутаций и популяционной динамики, такие как модель Кимуры или модель Йохансона-Кинга. Эти модели учитывают вероятности различных типов мутаций и управляются параметрами, такими как скорость мутаций, размер популяции и другие факторы.

Для больших чисел предков может потребоваться использование специализированных программных пакетов или библиотек, которые предоставляют реализации этих моделей и позволяют проводить более сложные вычисления.



In [ ]:
from Bio.Phylo.TreeConstruction import DistanceCalculator
from Bio.Phylo.TreeConstruction import DistanceTreeConstructor
from Bio import AlignIO

# Загружаем последовательность ДНК
alignment = AlignIO.read("example_alignment.fasta", "fasta")

# Вычисляем матрицу расстояний с помощью модели Кимуры
calculator = DistanceCalculator('identity')
dm = calculator.get_distance(alignment)

# Строим дерево на основе матрицы расстояний
constructor = DistanceTreeConstructor()
tree = constructor.upgma(dm)

# Получаем количество предков из дерева
ancestors_count = len(tree.get_terminals())

print(f"Общее количество предков: {ancestors_count}")


**Модель Йохансона-Кинга.**

Модель Йохансона-Кинга (Johansen-King model) - это модель, используемая в физике и химии для описания взаимодействия между атомами и молекулами. В частности, она может использоваться для моделирования спектров атомов и молекул.

В Python модель Йохансона-Кинга может быть реализована с использованием различных библиотек, таких как NumPy, SciPy и другие библиотеки для научных вычислений. Однако, напрямую в библиотеках scikit-learn или других широко используемых библиотеках машинного обучения и анализа данных этой модели нет, поскольку она предназначена для физического моделирования.

Если у вас есть конкретные задачи или проблемы, связанные с моделью Йохансона-Кинга, пожалуйста, уточните ваш вопрос, и я постараюсь помочь вам более конкретно.

In [4]:
import numpy as np

def johansen_king_potential(r, a, b, c):
    return a * np.exp(-b * r) - c / (r**6)

# Пример использования
r_values = np.linspace(1, 10, 100)  # Значения расстояния r
a_value = 1.0  # Параметр a
b_value = 0.1  # Параметр b
c_value = 0.5  # Параметр c

potential_values = johansen_king_potential(r_values, a_value, b_value, c_value)


**Алгоритм для вычисления количества предков  по нуклеотидной последовательности**

Для вычисления количества предков по нуклеотидной последовательности можно использовать алгоритм подсчета числа нуклеотидов и их соответствующее преобразование в количество предков.
В этом алгоритме мы сначала подсчитываем количество каждого типа нуклеотида в последовательности. Затем мы предполагаем, что каждая пара нуклеотидов A-T и C-G представляет одного предка, и суммируем количество этих пар для получения общего количества предков.

Этот алгоритм позволяет вычислить количество предков на основе нуклеотидной последовательности.

In [5]:
def calculate_ancestors_from_sequence(sequence):
    num_A = sequence.count('A')
    num_C = sequence.count('C')
    num_G = sequence.count('G')
    num_T = sequence.count('T')

    # Предположим, что каждая пара нуклеотидов A-T и C-G представляет одного предка
    ancestors = (num_A + num_T) + (num_C + num_G)

    return ancestors

# Пример использования
dna_sequence = "ATCGATCGATCG"
total_ancestors = calculate_ancestors_from_sequence(dna_sequence)
print(f"Общее количество предков на основе последовательности {dna_sequence}: {total_ancestors}")


Общее количество предков на основе последовательности ATCGATCGATCG: 12


**Алгоритм для вычисления количества предков с потерей.**

В этой реализации алгоритма мы также используем цикл for для итерации по каждому потомку от 1 до заданного количества потомков. Мы добавляем значение текущего потомка к общему количеству предков, но при этом уменьшаем общее количество предков на 1 для каждого второго потомка (таким образом, происходит "потеря" предка).

Таким образом, данный алгоритм учитывает потерю предков и возвращает общее количество предков с учетом этой потери.

In [6]:
def calculate_ancestors_with_loss(descendants):
    ancestors = 0
    for i in range(1, descendants + 1):
        ancestors += i
        if i % 2 == 0:
            ancestors -= 1  # Потеря одного предка на каждого второго потомка
    return ancestors

# Пример использования
num_descendants = 5
total_ancestors_with_loss = calculate_ancestors_with_loss(num_descendants)
print(f"Общее количество предков с потерей, начиная с {num_descendants} потомков: {total_ancestors_with_loss}")


Общее количество предков с потерей, начиная с 5 потомков: 13


**Алгоритм для вычисления количества предков начиная с первого порядка потомков.**

Этот код определяет функцию calculate_ancestors_from_descendants, которая принимает количество потомков и возвращает общее количество предков, начиная с этих потомков. В цикле происходит итерация по каждому потомку, и к общему количеству предков добавляется текущее значение потомка. После этого значение потомка уменьшается на 1, и цикл продолжается до тех пор, пока значение потомка не станет равным 0. В конце кода приведен пример использования этой функции для вычисления общего количества предков, начиная с 5 потомков.

Это простой пример, и в реальности может потребоваться более сложный метод, чтобы учесть различные особенности генеалогических деревьев.

In [7]:
def calculate_ancestors_from_descendants(descendants):
    ancestors = 0
    while descendants > 0:
        ancestors += descendants
        descendants -= 1
    return ancestors

# Пример использования
num_descendants = 5
total_ancestors = calculate_ancestors_from_descendants(num_descendants)
print(f"Общее количество предков, начиная с {num_descendants} потомков: {total_ancestors}")



Общее количество предков, начиная с 5 потомков: 15


**Алгоритм для вычисления количества предков **

Этот код определяет функцию calculate_ancestors, которая принимает количество поколений и возвращает общее количество предков в генеалогическом дереве. В цикле происходит итерация по каждому поколению и добавление к общему количеству предков значения 2 в степени номера поколения. В конце кода приведен пример использования этой функции для вычисления общего количества предков за 5 поколений.

Это простой пример, и в реальности могут потребоваться более сложные методы, чтобы учесть различные особенности генеалогических деревьев.

In [8]:
def calculate_ancestors(generations):
    ancestors = 0
    for i in range(1, generations + 1):
        ancestors += 2 ** i
    return ancestors

# Пример использования
num_generations = 5
total_ancestors = calculate_ancestors(num_generations)
print(f"Общее количество предков за {num_generations} поколений: {total_ancestors}")


Общее количество предков за 5 поколений: 62


**Жадный алгоритм **

Жадный алгоритм - это метод решения задачи оптимизации, при котором на каждом шаге выбирается оптимальное решение, приводящее к локальной оптимизации, с надеждой на достижение глобальной оптимизации. Для вычисления количества предков питона можно использовать жадный алгоритм, который будет последовательно подниматься по иерархии предков питона, начиная с заданного питона и подсчитывая количество предков.


В этом примере count_ancestors - это функция, которая принимает название питона и словарь, содержащий информацию о предках, и возвращает количество предков этого питона. Затем мы используем эту функцию для вычисления количества предков для заданного питона "python" и словаря предков "ancestors".

Это простой пример реализации жадного алгоритма для вычисления количества предков питона. Реальная реализация может быть более сложной и учитывать различные случаи, такие как циклические зависимости или отсутствие предков.

In [9]:
def count_ancestors(snake, ancestors_map):
    count = 0
    current_snake = snake
    while current_snake in ancestors_map:
        count += 1
        current_snake = ancestors_map[current_snake]
    return count

# Пример использования
ancestors = {
    "python": "reptile",
    "reptile": "animal",
    "animal": "organism"
}

snake = "python"
ancestor_count = count_ancestors(snake, ancestors)
print(f"Количество предков у питона: {ancestor_count}")


Количество предков у питона: 3
